<?php

namespace ET\ETGestBundle\Repository;

/**
 * AllegatiV2Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AllegatiV2Repository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param array $filters
     * @return Array
     */
	public function findAttachmentsTypeByParentId($select = '', $ids = array())
	{
		if(!$ids) return;

		$qb = $this->getEntityManager()->createQueryBuilder('a');
		$qb->select('a.parentId AS id_modulo');
		$qb->addSelect('a.type AS tipoDocumento');
		$qb->addSelect('COUNT(a) AS numero_allegati');
		$qb->addSelect('2 AS versione');
		$qb->addSelect("'{$select}' AS tipo");
		$qb->from('ETGestBundle:AllegatiV2','a');
		$qb->where('a.parentId IN (:ids)');
		$qb->andWhere('a.type = :type');
		$qb->setParameters(array(
			'ids'  => $ids,
			'type' => 'documento'
		));
		$qb->groupBy('a.parentId, a.type');

		return $qb->getQuery()->getResult();
	}

	/**
	 * @param int $id
     * @return Array
     */
	public function findAttachmentsPathByParentId($id)
	{
		if(!$id) return;

		$qb = $this->getEntityManager()->createQueryBuilder('a');
		$qb->select('a.path, a.file, a.caption');
		$qb->from('ETGestBundle:AllegatiV2','a');
		$qb->where('a.type IN (:type)');
		$qb->andWhere('a.parentId = :id');
		$qb->setParameters(array(
			'id'  => $id,
			'type' => array('documento', 'servizio')
		));

		return $qb->getQuery()->getResult();
	}
}
