<?php

namespace ET\ETGestBundle\Repository;

/**
 * AnagraficheContattiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnagraficheContattiRepository extends \Doctrine\ORM\EntityRepository
{
}
