<?php

namespace ET\ETGestBundle\Repository;

/**
 * IsoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IsoRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableCountryCode() {
        return $this->getEntityManager()
            ->createQueryBuilder('a')
            ->select('a.prefissointernazionale, a.stato')
            ->from('ETGestBundle:Iso','a')
            ->where('a.prefissointernazionale IS NOT NULL')
            ->andWhere("a.prefissointernazionale != ''")
            ->orderBy('a.stato', 'ASC')
            ->getQuery()->getResult();   
    }

    /**
     * @param boolean returnAssociativeArray
     * @return Array
     */
    public function findAllCountryCode($returnAssociativeArray = false) 
    {
        $result = $this->getEntityManager()
            ->createQueryBuilder('i')
            ->select('i.codice AS chiave, i.stato AS descri, i.comunitaria, i.tipologianazione AS tipoDestinazione')
            ->from('ETGestBundle:Iso', 'i')
            ->orderBy('i.stato')
            ->getQuery()->getResult();

        if($returnAssociativeArray == true) {
            foreach($result as $key=>$res) {
                $tmp = $key;
                $key = $res['chiave'];
                $result[$key] = $res;
                unset($result[$tmp]);
            }
        }

        return $result;
    }
}
