<?php

namespace ET\ETGestBundle\Repository;

/**
 * ModuloStornoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuloStornoRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * @return Array
     */
	public function findTravelWithPaymentStatusSettledByTravelStatusAndRegistryId($status, $id)
	{
		$sql = "SELECT vg.id_viaggio, vg.id_anagrafica, vg.tipologia, vg.descrizione, DATE_FORMAT(vg.dataInizioViaggio, '%d-%b-%y') AS dataInizioViaggio, DATE_FORMAT(vg.dataFineViaggio, '%d-%b-%y') AS dataFineViaggio
				FROM `modulo_storno` m 
				JOIN `viaggi` vg ON (m.id_viaggio = vg.id_viaggio)
				INNER JOIN `vacanzev_agenti`.`users` u ON (m.codPromotore = u.id)
				WHERE m.statoPagamento != 'saldato'
				AND vg.status <= {$status}
				AND vg.id_anagrafica = '{$id}'
				ORDER BY vg.id_viaggio";

		$stmt  = $this->getEntityManager()->getConnection()->prepare($sql);
		$stmt->execute();
		return $stmt ->fetchAll();
	}
}
