<?php

namespace ET\ETGestBundle\Repository;

/**
 * PagamentiDettagliEtgestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagamentiDettagliEtgestRepository extends \Doctrine\ORM\EntityRepository
{
}
