<?php

namespace ET\ETGestBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param array $filters
     * @return Array
     */
	public function findTicketsBy($filters = array(), $returnArr = false)
	{
		if(empty($filters)) return null;

		$condition = '';
		$conparationOperator = 'LIKE';
		$parameters = array();
		$index = 0;

		$qb = $this->getEntityManager()->createQueryBuilder('t');
		$qb->select('DISTINCT t.idTicket, t.idViaggio');
		$qb->from('ETGestBundle:Ticket','t');

		foreach($filters as $key => $val) {
			$index++;

			if(is_numeric($val)) {
				$conparationOperator = '=';
			} else {
				$conparationOperator = 'LIKE';
			}

			$condition .= 't.'.$key.' '.$conparationOperator.' :'.$key;
			if($index<count($filters)) {
				$condition .= ' AND ';
			}
			$parameters[$key] = $val;
		}

		$qb->where($condition);
		$qb->setParameters($parameters);

		if($returnArr == true)
			return $qb->getQuery()->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);

		return $qb->getQuery()->getResult();
	}
}
