imports:
    - { resource: parameters.eu.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: idetus
        connections:
            agenti:
                driver:   pdo_mysql
                host:     "%database_host_agenti%"
                port:     "%database_port%"
                dbname:   "%database_name_agenti%"
                user:     "%database_user_agenti%"
                password: "%database_password_agenti%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text
            romano:
                driver:   pdo_mysql
                host:     "%database_host_romano%"
                port:     "%database_port%"
                dbname:   "%database_name_romano%"
                user:     "%database_user_romano%"
                password: "%database_password_romano%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text
            idetus:
                driver:   pdo_mysql
                host:     "%database_host_idetus%"
                port:     "%database_port%"
                dbname:   "%database_name_idetus%"
                user:     "%database_user_idetus%"
                password: "%database_password_idetus%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text
            etticket:
                driver:   pdo_mysql
                host:     "%database_host_etticket%"
                port:     "%database_port%"
                dbname:   "%database_name_etticket%"
                user:     "%database_user_etticket%"
                password: "%database_password_etticket%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text
            listanozze:
                driver:   pdo_mysql
                host:     "%database_host_listanozze%"
                port:     "%database_port%"
                dbname:   "%database_name_listanozze%"
                user:     "%database_user_listanozze%"
                password: "%database_password_listanozze%"
                charset:  UTF8
                mapping_types:
                    enum: string
                    set: string
                    varbinary: string
                    tinyblob: text
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
        default_entity_manager: idetus
        entity_managers:
            idetus:
                connection: idetus
                mappings:
                    ETGestBundle: ~
            agenti:
                connection: agenti
                mappings:
                    AppBundle: ~
            romano:
                connection: romano
                mappings:
                    AppBundle: ~
            etticket:
                connection: etticket
                mappings:
                    ETTicketBundle: ~
            listanozze:
                connection: listanozze
                mappings:
                    AppBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
