<?php

namespace ET\ETBackofficeBundle\Repository;

/**
 * BackofficePortaliMercatiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackofficePortaliMercatiRepository extends \Doctrine\ORM\EntityRepository {

    public function getAvailableProduct() {
        return $this->getEntityManager()
                ->createQueryBuilder('a')
                ->select('a.nomeportale, a.fcd')
                ->from('ETBackofficeBundle:BackofficePortaliMercati', 'a')
                ->where("a.mercato = :mercato")
                ->andWhere("a.attivo = :attivo")
                ->orderBy('a.nomeportale', 'ASC')
                ->setParameter('mercato', 'ITA')
                ->setParameter('attivo', 1)
                ->getQuery()
                ->getResult();
    }

}
