<?php

namespace ET\UserBundle\Repository;

/**
 * TraduzioniRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraduzioniRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAvailableLanguage() 
    {        
        
        $stmt = $this->getEntityManager()
        ->getConnection()
        ->prepare("SHOW COLUMNS FROM `traduzioni` LIKE 'lingua_%'");

        $stmt->execute();
        $arrayFields = $stmt->fetchAll();
        
        $arrayLanguage = array();
        
        if (count($arrayFields) > 0) {
            foreach ($arrayFields as $singleField) {
                $arrayLanguage[] = str_replace('lingua_', '', $singleField['Field']);
            }
        }
        
        return $arrayLanguage;
    }
}
