<?php

namespace ET\ETTicketBundle\Repository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * @param array $filters
     * @return Array
     */
	public function findRequestBy($filters = array(), $returnArr = false)
	{
		if(empty($filters)) return null;

		$condition = '';
		$conparationOperator = 'LIKE';
		$parameters = array();
		$index = 0;

		$qb = $this->getEntityManager()->createQueryBuilder('req');
		$qb->select('req');
		$qb->from('ETTicketBundle:Request','req');

		foreach($filters as $key => $val) {
			$index++;

			if(is_numeric($val)) {
				$conparationOperator = '=';
			} else {
				$conparationOperator = 'LIKE';
			}

			$condition .= 'req.'.$key.' '.$conparationOperator.' :'.$key;
			if($index<count($filters)) {
				$condition .= ' AND ';
			}
			$parameters[$key] = $val;
		}

		$qb->where($condition);
		$qb->setParameters($parameters);

		if($returnArr == true)
			return $qb->getQuery()->getResult(\Doctrine\ORM\AbstractQuery::HYDRATE_ARRAY);

		return $qb->getQuery()->getResult();
	}
}
